name: upscaler
description: "Upscale images to exact 3840x2160 Samsung Frame TV art."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.4

dependencies:
  desktop_drop: ^0.8.4
  file_selector: ^1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
